### ISSUE TITLE
@enumToInt error with Zig 11 and Playdate SDK 2.0 (Mac)

### ISSUE THREAD

**Issue by markd2** [DanB91/Zig-Playdate-Template#1]
Hi!  I'm guessing SDK 2.0 support isn't available now.  Anything the community can do to help?  (I'm a zig n00b - just got through 3/4 of ziglings over the weekend, but have been around the block in general mac tech for a while)

In particular, I'm getting an error not finding `@enumToInt`

* Mac Ventura 13.4
* zig version: 0.11.0-dev.3777+64f0059cd
* Playdate SDK: 2.0.0
* Path to objcopy: /opt/homebrew/Cellar/binutils/2.40/bin/objcopy

here's the full run of `zig build`
```
zig build-lib pdex Debug native: error: the following command failed with 1 compilation errors:
/Users/markd/Projects/thirdparty/zig/zig-11/zig build-lib /Users/markd/Projects/RandomLearning/zig/zigdate/Zig-Playdate-Template/src/main.zig --cache-dir /Users/markd/Projects/RandomLearning/zig/zigdate/Zig-Playdate-Template/zig-cache --global-cache-dir /Users/markd/.cache/zig --name pdex -dynamic -install_name @rpath/libpdex.dylib --listen=- 
Build Summary: 0/9 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
+- run /Users/markd/Developer/PlaydateSDK/bin/pdc transitive failure
   +- run objcopy transitive failure
      +- run cp transitive failure
         +- run mv transitive failure
            +- install pdex.elf transitive failure
               +- zig build-exe pdex.elf Debug thumb-freestanding-eabihf transitive failure
                  +- install pdex transitive failure
                     +- zig build-lib pdex Debug native 1 errors
src/main.zig:29:29: error: invalid builtin function: '@enumToInt'
```

and the line of code in question:
```
    playdate.graphics.clear(@enumToInt(pdapi.LCDSolidColor.ColorWhite));
```

Thanks!

**Comment by DanB91** [comment]
Hi @markd2,

Yes I am currently working on SDK 2.0 support, which will require a change in Zig itself unfortunately (see https://devforum.play.date/t/error-compress-failed-buffer-is-empty-error-from-pdc-in-sdk-2-0-beta-2/11474/21 if you are interested) .  

However, this issue is due to the fact that many of Zig built-ins were very recently renamed.  So in this, case I believe `@enumToInt` should now be `@intFromEnum`.  There are probably other builtins you will need to fix. When I update this template to 2.0, I will fix this.  

Please let me know if you run into anything else!

**Comment by markd2** [comment]
ooh nice!  Fixed a couple of others that were similarly renamed.  If you want a PR with those changes am happy to make one.

And I got to the `error: compress failed: buffer is empty` stage. Will be happy to try out stuff if you get past it!

Thanks!
